Practice2
YrShavlak/autoSchool pull request #2
Opened 2024-01-16 11:59 UTC by YrShavlak

2024-01-16 16:07 UTC, LevshinNIX requested changes

2024-01-16 16:07 UTC, LevshinNIX commented on .idea/src/main/Java_Practice2/UpdateValues.java
> +        int newC = a + b + c;
Это задание решается без ввода дополнительных переменных

2024-01-17 11:37 UTC, YrShavlak commented on .idea/src/main/Java_Practice2/UpdateValues.java
> +        int newC = a + b + c;
changes were added

2024-01-17 12:08 UTC, LevshinNIX approved these changes

2024-01-18 16:19 UTC, merged